# Copyright 2010 Hannes Baldursson. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc #$(GOARCH)

TARG=go-idn.googlecode.com/hg/src/punycode
GOFILES=\
	punycode.go\
	
include $(GOROOT)/src/Make.pkg
