# Copyright 2010 Hannes Baldursson. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.$(GOARCH)

TARG=unicode/normalization
GOFILES=\
	normalization.go\
	tables.go\
	
	
include $(GOROOT)/src/Make.pkg
