# Copyright 2010 Hannes Baldursson. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# This file is part of go-idn

include $(GOROOT)/src/Make.inc #$(GOARCH)

TARG=idn/idna
GOFILES=\
	idna.go\
	

include $(GOROOT)/src/Make.pkg
